meta_product_name: "Mobler"
meta_title: "Mobler - Easy way to find furniture by size"
meta_description: "Not easy to find a piece of furniture of adequate dimensions. Mobler quickly finds you the perfect piece of furniture."
meta_image: "http://res.cloudinary.com/copas/image/upload/c_scale,h_630,w_1200/v1503928936/mobler_llvwr5.png"  # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
